# Generated by Django 4.1.4 on 2022-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.URLField()),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tags', models.TextField()),
                ('url_github', models.URLField()),
            ],
        ),
    ]
