# Generated by Django 4.1.4 on 2022-12-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='foto',
            field=models.ImageField(null=True, upload_to='proyectos'),
        ),
    ]
