# Generated by Django 4.1.4 on 2022-12-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_proyecto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tags',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
